---
apiVersion: v1
kind: Service
metadata:
  name: connect-db
  labels:
    name: connect-db
spec:
  ports:
    - port: 13306
      targetPort: 3306
  selector:
    app: connect-db
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: connect-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: connect-db
  template:
    metadata:
      labels:
        app: connect-db
    spec:
      containers:
        - args:
            - --character-set-server=utf8mb4
            - --collation-server=utf8mb4_unicode_ci
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: root
            - name: TZ
              value: Asia/Tokyo
          image: mysql:8.0
          name: connect-db
          ports:
            - containerPort: 3306
          resources: {}
