---
apiVersion: v1
kind: Service
metadata:
  name: connect-webapp
  labels:
    name: connect-webapp
spec:
  type: NodePort
  ports:
    - port: 18081
      targetPort: 18081
  selector:
    app: connect-webapp
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: connect-webapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: connect-webapp
  template:
    metadata:
      labels:
        app: connect-webapp
    spec:
      containers:
        - env:
            - name: server.port
              value: "18081"
            - name: spring.datasource.url
              value: jdbc:mysql://connect-db:13306/webapp
          image: nexti4hack/connect-webapp:1.0.0
          name: connect-webapp
          ports:
            - containerPort: 18081
          resources: {}
