version: '3'
services:
    # Webapp DB
    webapp-db:
        image: mysql:8.0
        container_name: webapp-db
        restart: always
        ports:
            - "13306:3306"
        volumes:
            # 初期データ
            - ../db/ddl:/docker-entrypoint-initdb.d
            # 永続化
            - ./db/mysql_data:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: root
            TZ: 'Asia/Tokyo'
        command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
        networks:
            - webapp-network
networks:
    webapp-network: